---
# roles/launch_app/tasks/main.yml
- name: Run HTTPD
  docker_container:
    name: httpd
    image: tp-devops-httpd
    state: started
    env:
      VAR_NAME: value  # Add environment variables as needed
