name: Test Backend

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build, test, and analyze with SonarCloud
        run: mvn -B verify sonar:sonar 
          -Dsonar.projectKey=michi-mourchid_devops-livecoding 
          -Dsonar.organization=michi-mourchid 
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          --file ./simple-api/pom.xml
        working-directory: ./simple-api
